kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: docker/compose:1.27.4
  privileged: true
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  commands:
    - echo hello
    - docker-compose --version
    - echo world

trigger:
  event:
    include:
    - push
    - pull_request
