kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - docker-compose --version
  - echo world

trigger:
  event:
    include:
    - push
    - pull_request
