kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: docker/compose:1.27.4
  # privileged: true
  volumes:
    - name: docker-socket
      path: /var/run/docker.sock
  commands:
    - echo hello
    - docker-compose -f docker-compose.yml up
    - echo world

trigger:
  event:
    include:
    - push
    - pull_request


# -----------------------------------------------------------------------------
#                                     Volumes
# -----------------------------------------------------------------------------
volumes:
  - name: docker-socket
    host:
      path: /var/run/docker.sock
